version: 2
jobs:
 build:
   docker:
     - image: circleci/golang:1.12
   steps:
     - setup_remote_docker
     - checkout
     - run: wget https://github.com/sharkdp/hyperfine/releases/download/v1.5.0/hyperfine_1.5.0_amd64.deb
     - run: sudo dpkg -i hyperfine_1.5.0_amd64.deb
     - run: sudo apt update && sudo apt install parallel
     - run: ./build.sh
     - run: ./run.sh
