version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - wget https://github.com/sharkdp/hyperfine/releases/download/v1.5.0/hyperfine_1.5.0_amd64.deb
     - sudo dpkg -i hyperfine_1.5.0_amd64.deb
     - sudo apt update && sudo apt install parallel
     - ./build.sh
     - ./run.sh
