version: 2.1
jobs:
 skip:
   steps:
     - run: echo "build for public-registry-benchmarks ONLY run every day at 12:00"
 build:
   docker:
     - image: circleci/golang:1.12
   steps:
     - setup_remote_docker
     - checkout
     - run: wget https://github.com/sharkdp/hyperfine/releases/download/v1.5.0/hyperfine_1.5.0_amd64.deb
     - run: echo "8ed797c6a0ba0b9e7886b70ff493bc3448293e3e hyperfine_1.5.0_amd64.deb" | sha1sum -c -
     - run: sudo dpkg -i hyperfine_1.5.0_amd64.deb
     - run: rm hyperfine_1.5.0_amd64.deb
     - run: sudo apt update && sudo apt install parallel
     - run: ./build.sh
     - run:
         command: ./run.sh
         no_output_timeout: 30m
     - add_ssh_keys:
         fingerprints:
           - "2e:f7:80:fd:0a:eb:98:b5:c9:e9:ee:dc:d7:35:ee:3f"
     - run: ./archive-report.sh
workflows:
  version: 2
  commit:
    jobs:
      - skip
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
